// Type definitions for personality-based planet system

export interface ThemeNode {
  // Unique identifier for this theme
  id: string;

  // Theme information
  name: string;
  description: string;

  // Hierarchy level (theme -> subtheme -> topic -> detail)
  level: 'theme' | 'subtheme' | 'topic' | 'detail';

  // Visual properties
  visualProperties: {
    color: string;
    size: 'small' | 'medium' | 'large';
    imageAsset?: string;
  };

  // Data sources that contributed to this theme
  dataSources: {
    spotify?: {
      weight: number; // 0-1, how much Spotify data influenced this theme
      examples?: string[]; // e.g., song names, artists
    };
    gmail?: {
      weight: number;
      examples?: string[]; // e.g., email subjects, contacts
    };
    search?: {
      weight: number;
      examples?: string[]; // e.g., search queries
    };
  };

  // Tree structure
  parentId: string | null;
  childIds: string[];

  // Orbital properties (for visualization)
  orbitProperties?: {
    orbitRadius: number;
    orbitSpeed: number;
    angle: number;
  };
}

export interface PersonalityTree {
  // Metadata about the analysis
  userId: string;
  generatedAt: Date;
  dataTimeRange: {
    start: Date;
    end: Date;
  };

  // The actual tree of themes
  nodes: ThemeNode[];

  // Root theme IDs (top-level themes)
  rootThemeIds: string[];

  // Summary generated by LLM
  summary: string;
}

// Helper type for the LLM to generate
export interface LLMThemeInput {
  name: string;
  description: string;
  level: 'theme' | 'subtheme' | 'topic' | 'detail';
  dataSources: {
    spotify?: { weight: number; examples?: string[] };
    gmail?: { weight: number; examples?: string[] };
    search?: { weight: number; examples?: string[] };
  };
  children?: LLMThemeInput[];
}
